name: Update Stock Data

on:
  schedule:
    - cron: "25 1 * * 1-5"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run stock update
        run: python scripts/update_data.py

      - name: Analyze stocks
        run: python scripts/analyze_stock.py
